apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: roboshop-ingress
  namespace: roboshop
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'

spec:
  ingressClassName: alb

  rules:
  - http:
      paths:

      # Frontend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80

      # Catalogue
      - path: /catalogue
        pathType: Prefix
        backend:
          service:
            name: catalogue
            port:
              number: 8080

      # User
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: user
            port:
              number: 8080

      # Cart
      - path: /cart
        pathType: Prefix
        backend:
          service:
            name: cart
            port:
              number: 8080

      # Shipping
      - path: /shipping
        pathType: Prefix
        backend:
          service:
            name: shipping
            port:
              number: 8080

      # Payment
      - path: /payment
        pathType: Prefix
        backend:
          service:
            name: payment
            port:
              number: 8080
